### ISSUE TITLE
Dataset Information

### ISSUE THREAD

**Issue by harshit-333** [mboccenti/Recommender_system_project#1]
Sir, can you please tell me where did you get the link to this dataset or how did you access this dataset?

**Comment by mboccenti** [comment]
The datasets are stored in the cloud as per the lab instructions. 

`# Point to the datasets stored on the cloud`
`course_genre_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/course_genre.csv"`

`ratings_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-ML321EN-SkillsNetwork/labs/datasets/ratings.csv"`

you can access them as Pandas dataframes:
`course_df = pd.read_csv(course_genre_url)`
`ratings_df = pd.read_csv(ratings_url)`

**Comment by harshit-333** [comment]
That means you just used this link directly to get the .CSV files? I might
be asked where I got this dataset from so what should be my answer since I
can't just show them this link as it will not look authentic.

So it would be helpful if you tell me something more about this dataset
like where is this collected from or how to access it manually from Google
or something like that.

**Comment by mboccenti** [comment]
Sure thing. 

This project contains the datasets and the exercises for the IBM Machine Learning Certification labs by [Yan Luo](https://www.linkedin.com/in/yan-luo-96288783).
[https://www.coursera.org/professional-certificates/ibm-machine-learning](https://www.coursera.org/professional-certificates/ibm-machine-learning)

Thanks.

**Comment by harshit-333** [comment]
So that means the dataset is not publicly available like on kaggle or other open source apart from the .csv
link you shared right!

**Comment by mboccenti** [comment]
I could not answer that. If you would like more information about the origin and availability of the datasets, you should ask the dataset and course's author, whose link I provided
.
This project contains my notes and exercises for the course. Cheers.
